schema_version: "1.0"
id: cbn_sky_island
display_name: Sky Island
short_description: >-
  Cataclysm BN port of the Sky Island mod. Raid-based gameplay inspired by
  Escape from Tarkov and Dark & Darker. This is a very early version!
description: >-
  Cataclysm BN port of the Sky Island mod. Raid-based gameplay inspired by
  Escape from Tarkov and Dark & Darker. This is a very early version!
author:
  - "Original: TGWeaver"
  - "BN Port: grayson and Claude :)"
license: CC-BY-SA-4.0
homepage: "https://github.com/graysonchao/CBN-Sky-Island"
version: v0.0.7-alpha
dependencies:
  bn: ">=0.9.1"
source:
  type: github_archive
  url: >-
    https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.7-alpha.zip
  commit_sha: f0360b0948989847e77de10d16c74ebb7a11469c
autoupdate:
  type: tag
last_updated: "2026-01-07T13:30:31.938Z"
previous_releases:
  - version: v0.0.6-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.6-alpha.zip
      commit_sha: 4b50d4170844b669c4652299a833e032b9e98c37
  - version: v0.0.5-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.5-alpha.zip
      commit_sha: 9a0b541d7e700cbd1bcbd3eec8e29cc487ac9f01
  - version: v0.0.4-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.4-alpha.zip
      commit_sha: 6d922a64839a76ad25666f74f713d6a9c651ab79
  - version: v0.0.3-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.3-alpha.zip
      commit_sha: 3fdeb753d8086cd80f69bb70291340b1a9689f23
  - version: v0.0.2-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.2-alpha.zip
      commit_sha: 3820140f6e9cc1239e58723c4f1a770b8575f4e5
  - version: v0.0.1-alpha
    source:
      type: github_archive
      url: >-
        https://github.com/graysonchao/CBN-Sky-Island/archive/refs/tags/v0.0.1-alpha.zip
      commit_sha: 7d0aacb2f28fdad610ef1982d3e26feea51c05bf
